init: start sprint-2
ClevertecFrontendLab/ILYA-DUBINA pull request #2
Opened 2024-02-27 16:06 UTC by ILYA-DUBINA

2024-02-27 16:09 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 85%.
Общее количество тестов: 7.
Количество непройденных тестов: 1.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/reg-success-2.png)
***
**sprint 2 -- change-pass-error (failed).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709050140/sprint%202%20--%20change-pass-error%20(failed).png)

2024-02-27 17:08 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 85%.
Общее количество тестов: 7.
Количество непройденных тестов: 1.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/reg-success-2.png)
***
**sprint 2 -- change-pass-error (failed).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709053733/sprint%202%20--%20change-pass-error%20(failed).png)

2024-02-27 17:13 UTC, Ivan6813 approved these changes

2024-02-27 19:42 UTC, ValadzkoAliaksei requested changes

2024-02-27 19:42 UTC, ValadzkoAliaksei commented on package.json
> +        "antd": "^5.14.1",
андтдизайн должен быть 4+ это указано в инструкции много раз говорилось

2024-02-27 19:42 UTC, ValadzkoAliaksei commented on package.json
> +        "redux-thunk": "^3.1.0"
санки есть в тулките, их ставить не надо

2024-02-27 19:42 UTC, ValadzkoAliaksei commented on src/global/component/ErrorAndWarningComponent.tsx
> +                            warningContent === 'successReg'
очень страшно... сделай селектор
объект и ищи в нем значения по ключам

2024-02-27 19:42 UTC, ValadzkoAliaksei commented on src/global/component/ErrorAndWarningComponent.tsx
> +                            warningContent === 'success'
и тут

2024-02-28 07:32 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 85%.
Общее количество тестов: 7.
Количество непройденных тестов: 1.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/reg-success-2.png)
***
**sprint 2 -- change-pass-error (failed).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/ILYA-DUBINA/1709105534/sprint%202%20--%20change-pass-error%20(failed).png)

2024-02-28 08:05 UTC, ValadzkoAliaksei approved these changes

2024-02-28 08:33 UTC, closed without merging

2024-02-28 08:57 UTC, ILYA-DUBINA commented
Здравствуйте, нужно 2 аппрува ментора что бы залить проект? Просто волнуюсь залился ли проект.